export const OPENED_PREFIX_MAP: Record<string, string> = {
  en: "opened",
  es: "abierto",
  fr: "ouvert",
  de: "geöffnet",
  pt: "aberto",
  it: "aperto",
  nl: "geopend",
  ru: "открыт",
  ja: "作成",
  ko: "열림",
  zh: "打开",
  pl: "otwarty",
  tr: "açıldı",
  sv: "öppnad",
  no: "åpnet",
  da: "åbnet",
  fi: "avattu",
  cs: "otevřeno",
  hu: "megnyitva",
  ro: "deschis",
};

export const PUSHED_PREFIX_MAP: Record<string, string> = {
  en: "pushed",
  es: "enviado",
  fr: "poussé",
  de: "gepusht",
  pt: "enviado",
  it: "pushato",
  nl: "gepusht",
  ru: "отправлено",
  ja: "プッシュ",
  ko: "푸시됨",
  zh: "推送",
  pl: "wypchnięto",
  tr: "gönderildi",
  sv: "pushad",
  no: "pushet",
  da: "pushet",
  fi: "pushattu",
  cs: "pushnuto",
  hu: "feltöltve",
  ro: "push-uit",
};
